import db from "../models/index.js";

export async function insertInitialData() {
  // Seed departments
  await db.Department.bulkCreate(
    [
      {
        departmentId: 1,
        departmentName: "Cardiology",
        location: "West Davidmouth",
      },
      {
        departmentId: 2,
        departmentName: "Neurology",
        location: "East Lisamouth",
      },
      {
        departmentId: 3,
        departmentName: "Oncology",
        location: "South Seth",
      },
      {
        departmentId: 4,
        departmentName: "Pediatrics",
        location: "Jillberg",
      },
      {
        departmentId: 5,
        departmentName: "Emergency",
        location: "South Danielstad",
      },
    ],
    {
      ignoreDuplicates: true,
    }
  );

  // Seed staff
  await db.Staff.bulkCreate(
    [
      {
        staffId: 1,
        lastName: "Berg",
        firstName: "Jason",
        gender: "Male",
        role: "Doctor",
        contact: "248.827.5047",
        specialization: "Interventional Cardiologist",
        departmentId: 1,
        doctorId: null,
      },
      {
        staffId: 2,
        lastName: "Adams",
        firstName: "Anna",
        gender: "Female",
        role: "Doctor",
        contact: "(819)706-2932x508",
        specialization: "Neurologist",
        departmentId: 2,
        doctorId: null,
      },
      {
        staffId: 3,
        lastName: "Sanchez",
        firstName: "Charles",
        gender: "Male",
        role: "Doctor",
        contact: "+1-956-218-1446x18491",
        specialization: "Interventional Cardiologist",
        departmentId: 1,
        doctorId: null,
      },
      {
        staffId: 4,
        lastName: "French",
        firstName: "Michelle",
        gender: "Male",
        role: "Doctor",
        contact: "789-609-7727",
        specialization: "Trauma Surgeon",
        departmentId: 5,
        doctorId: null,
      },
      {
        staffId: 5,
        lastName: "Washington",
        firstName: "Thomas",
        gender: "Male",
        role: "Doctor",
        contact: "425.424.3121x10342",
        specialization: "Cardiologist",
        departmentId: 1,
        doctorId: null,
      },
      {
        staffId: 6,
        lastName: "Clark",
        firstName: "Sergio",
        gender: "Male",
        role: "Nurse",
        contact: "001-714-866-5579",
        specialization: "",
        departmentId: 2,
        doctorId: 2,
      },
      {
        staffId: 7,
        lastName: "Cruz",
        firstName: "Jose",
        gender: "Male",
        role: "Nurse",
        contact: "375.481.0411x309",
        specialization: "",
        departmentId: 5,
        doctorId: 4,
      },
      {
        staffId: 8,
        lastName: "Ayala",
        firstName: "Guy",
        gender: "Male",
        role: "Nurse",
        contact: "605.319.3972",
        specialization: "",
        departmentId: 4,
        doctorId: 5,
      },
      {
        staffId: 9,
        lastName: "Rodriguez",
        firstName: "Kelsey",
        gender: "Female",
        role: "Nurse",
        contact: "(214)369-8421x0143",
        specialization: "",
        departmentId: 1,
        doctorId: 1,
      },
      {
        staffId: 10,
        lastName: "Arnold",
        firstName: "Paula",
        gender: "Female",
        role: "Nurse",
        contact: "646.651.3182",
        specialization: "",
        departmentId: 3,
        doctorId: 3,
      },
      {
        staffId: 11,
        lastName: "Mitchell",
        firstName: "Theresa",
        gender: "Male",
        role: "Nurse",
        contact: "001-420-949-2356",
        specialization: "",
        departmentId: 2,
        doctorId: 2,
      },
      {
        staffId: 12,
        lastName: "Edwards",
        firstName: "Karen",
        gender: "Male",
        role: "Nurse",
        contact: "482.382.3668",
        specialization: "",
        departmentId: 1,
        doctorId: 3,
      },
      {
        staffId: 13,
        lastName: "Lee",
        firstName: "Paul",
        gender: "Male",
        role: "Nurse",
        contact: "886-543-8348x7426",
        specialization: "",
        departmentId: 3,
        doctorId: 3,
      },
      {
        staffId: 14,
        lastName: "Taylor",
        firstName: "Ian",
        gender: "Female",
        role: "Nurse",
        contact: "(550)846-2495",
        specialization: "",
        departmentId: 1,
        doctorId: 5,
      },
      {
        staffId: 15,
        lastName: "Hill",
        firstName: "Valerie",
        gender: "Female",
        role: "Nurse",
        contact: "982-454-0876x5542",
        specialization: "",
        departmentId: 5,
        doctorId: 4,
      },
      {
        staffId: 16,
        lastName: "Zuniga",
        firstName: "Phyllis",
        gender: "Female",
        role: "Receptionist",
        contact: "761.789.8950",
        specialization: "",
        departmentId: 1,
        doctorId: null,
      },
      {
        staffId: 17,
        lastName: "Parker",
        firstName: "Brent",
        gender: "Female",
        role: "Receptionist",
        contact: "530-549-4941",
        specialization: "",
        departmentId: 5,
        doctorId: null,
      },
      {
        staffId: 18,
        lastName: "Hill",
        firstName: "Stephen",
        gender: "Female",
        role: "Receptionist",
        contact: "738.745.0792x895",
        specialization: "",
        departmentId: 5,
        doctorId: null,
      },
      {
        staffId: 19,
        lastName: "King",
        firstName: "Brian",
        gender: "Male",
        role: "Receptionist",
        contact: "001-535-431-2550x4558",
        specialization: "",
        departmentId: 1,
        doctorId: null,
      },
      {
        staffId: 20,
        lastName: "Beck",
        firstName: "Angela",
        gender: "Male",
        role: "Receptionist",
        contact: "+1-869-614-0739x61174",
        specialization: "",
        departmentId: 2,
        doctorId: null,
      },
    ],
    { ignoreDuplicates: true }
  );

  // Seed patients
  await db.Patient.bulkCreate(
    [
      {
        patientId: 1,
        lastName: "Noble",
        firstName: "Gabriel",
        height: 189,
        weight: 82,
        dateOfBirth: "2003-08-14",
        address: "51697 Rebecca Rest Joeport, VA 40886",
        contact: "515.673.1804x819",
        email: "dward@example.org",
      },
      {
        patientId: 2,
        lastName: "Evans",
        firstName: "Rhonda",
        height: 145,
        weight: 74,
        dateOfBirth: "1940-03-04",
        address: "12403 Suzanne Ports Apt. 034 New Kevin, NM 70009",
        contact: "392-887-2296x8053",
        email: "joneschad@example.com",
      },
      {
        patientId: 3,
        lastName: "Butler",
        firstName: "Karen",
        height: 195,
        weight: 57,
        dateOfBirth: "1969-09-14",
        address: "8433 Brittany Avenue Travisshire, VT 67238",
        contact: "(563)426-9748",
        email: "nancybanks@example.com",
      },
      {
        patientId: 4,
        lastName: "Mcdonald",
        firstName: "Jose",
        height: 164,
        weight: 80,
        dateOfBirth: "2016-10-31",
        address: "7133 Choi Trace Michaelville, MT 03231",
        contact: "(886)253-8308x2196",
        email: "megancollins@example.org",
      },
      {
        patientId: 5,
        lastName: "Dickson",
        firstName: "Nicholas",
        height: 169,
        weight: 91,
        dateOfBirth: "1942-11-21",
        address: "0964 Krause Burgs Apt. 432 South Tanya, AK 80960",
        contact: "982-320-6452x5148",
        email: "samantha92@example.org",
      },
      {
        patientId: 6,
        lastName: "Murphy",
        firstName: "Christopher",
        height: 150,
        weight: 92,
        dateOfBirth: "1980-04-05",
        address: "0624 Rhonda Throughway Suite 299 Phillipsmouth, WY 08320",
        contact: "001-683-907-8562x344",
        email: "stevenwilliams@example.net",
      },
      {
        patientId: 7,
        lastName: "Klein",
        firstName: "Kathryn",
        height: 162,
        weight: 71,
        dateOfBirth: "1959-03-16",
        address: "30862 Morse Alley East Cliffordview, SC 02128",
        contact: "(939)916-0676",
        email: "nduncan@example.net",
      },
      {
        patientId: 8,
        lastName: "Livingston",
        firstName: "Erin",
        height: 182,
        weight: 79,
        dateOfBirth: "2003-01-14",
        address: "612 James Flats Lake Andreaport, MA 97790",
        contact: "734-694-6814x69125",
        email: "andres34@example.net",
      },
      {
        patientId: 9,
        lastName: "Page",
        firstName: "Jacob",
        height: 184,
        weight: 54,
        dateOfBirth: "1937-05-04",
        address: "50583 Elliott Canyon Apt. 280 Port Geraldside, MA 56493",
        contact: "213-718-5787",
        email: "ashleychen@example.com",
      },
      {
        patientId: 10,
        lastName: "White",
        firstName: "Eric",
        height: 178,
        weight: 66,
        dateOfBirth: "1946-12-26",
        address: "556 Flowers Lights South Kristatown, TN 38437",
        contact: "401-957-9374x94352",
        email: "bsmith@example.com",
      },
      {
        patientId: 11,
        lastName: "Lawson",
        firstName: "Christian",
        height: 174,
        weight: 76,
        dateOfBirth: "1987-05-27",
        address: "11172 Todd Passage Apt. 366 Tylerville, FL 92032",
        contact: "+1-777-858-6618",
        email: "hooddiane@example.net",
      },
      {
        patientId: 12,
        lastName: "Pittman",
        firstName: "Jimmy",
        height: 150,
        weight: 104,
        dateOfBirth: "2002-10-27",
        address: "114 Christopher Landing Huffburgh, HI 70811",
        contact: "001-241-356-2116x886",
        email: "pmorris@example.net",
      },
      {
        patientId: 13,
        lastName: "Johnson",
        firstName: "Jean",
        height: 164,
        weight: 79,
        dateOfBirth: "1925-02-06",
        address: "2368 Patterson Squares Apt. 633 North Patrick, MI 32439",
        contact: "+1-712-645-6911x478",
        email: "hannah47@example.net",
      },
      {
        patientId: 14,
        lastName: "Martin",
        firstName: "Sara",
        height: 199,
        weight: 116,
        dateOfBirth: "2004-09-29",
        address: "4506 Vargas Meadows Apt. 886 Danafort, LA 77632",
        contact: "671.812.4994",
        email: "paulwhite@example.net",
      },
      {
        patientId: 15,
        lastName: "Peterson",
        firstName: "Timothy",
        height: 154,
        weight: 86,
        dateOfBirth: "1996-04-20",
        address: "28559 Shane Fields Suite 263 Nicholsonmouth, AZ 44776",
        contact: "810-797-9249",
        email: "wyatt21@example.net",
      },
      {
        patientId: 16,
        lastName: "Jenkins",
        firstName: "Alexandria",
        height: 193,
        weight: 52,
        dateOfBirth: "2003-02-05",
        address: "Unit 0234 Box 8478 DPO AE 24726",
        contact: "359.607.5415x3433",
        email: "josephalexander@example.net",
      },
      {
        patientId: 17,
        lastName: "Johnson",
        firstName: "Megan",
        height: 154,
        weight: 49,
        dateOfBirth: "1941-05-09",
        address: "PSC 0939, Box 8044 APO AE 51156",
        contact: "(301)285-1007x95359",
        email: "sandersrobert@example.net",
      },
      {
        patientId: 18,
        lastName: "Morales",
        firstName: "Rebecca",
        height: 191,
        weight: 85,
        dateOfBirth: "1968-06-22",
        address: "Unit 3913 Box 4712 DPO AE 90632",
        contact: "9607570282",
        email: "carterandrea@example.com",
      },
      {
        patientId: 19,
        lastName: "Ewing",
        firstName: "Mario",
        height: 165,
        weight: 79,
        dateOfBirth: "2018-08-31",
        address: "6835 Hayes Trail Lucasview, LA 49248",
        contact: "247.559.5852",
        email: "melissa73@example.org",
      },
      {
        patientId: 20,
        lastName: "Perez",
        firstName: "Danielle",
        height: 144,
        weight: 72,
        dateOfBirth: "1974-07-11",
        address: "627 Jennings Trafficway Holttown, MD 13673",
        contact: "894.515.8398x8939",
        email: "erichall@example.com",
      },
    ],
    { ignoreDuplicates: true }
  );

  // Seed appointments
  await db.Appointment.bulkCreate(
    [
      {
        appointmentId: 1,
        purpose: "Consultation",
        dateTime: "2025-10-21 07:17:51",
        status: "Cancelled",
        doctorId: 5,
        patientId: 1,
      },
      {
        appointmentId: 2,
        purpose: "General Care",
        dateTime: "2024-09-18 14:56:32",
        status: "Cancelled",
        doctorId: 1,
        patientId: 2,
      },
      {
        appointmentId: 3,
        purpose: "Consultation",
        dateTime: "2025-08-16 06:57:47",
        status: "Scheduled",
        doctorId: 2,
        patientId: 3,
      },
      {
        appointmentId: 4,
        purpose: "Consultation",
        dateTime: "2026-01-05 12:31:38",
        status: "Completed",
        doctorId: 1,
        patientId: 4,
      },
      {
        appointmentId: 5,
        purpose: "Consultation",
        dateTime: "2024-12-01 20:20:13",
        status: "Scheduled",
        doctorId: 5,
        patientId: 5,
      },
      {
        appointmentId: 6,
        purpose: "General Care",
        dateTime: "2025-03-19 06:21:10",
        status: "Scheduled",
        doctorId: 3,
        patientId: 6,
      },
      {
        appointmentId: 7,
        purpose: "Diagnostic & Testing",
        dateTime: "2026-02-28 01:05:11",
        status: "Scheduled",
        doctorId: 1,
        patientId: 7,
      },
      {
        appointmentId: 8,
        purpose: "General Care",
        dateTime: "2025-11-27 10:43:13",
        status: "Completed",
        doctorId: 3,
        patientId: 8,
      },
      {
        appointmentId: 9,
        purpose: "Follow Up",
        dateTime: "2025-02-09 00:11:06",
        status: "Completed",
        doctorId: 4,
        patientId: 9,
      },
      {
        appointmentId: 10,
        purpose: "Diagnostic & Testing",
        dateTime: "2026-06-07 20:21:31",
        status: "Scheduled",
        doctorId: 1,
        patientId: 10,
      },
      {
        appointmentId: 11,
        purpose: "General Care",
        dateTime: "2024-11-08 14:26:42",
        status: "Scheduled",
        doctorId: 2,
        patientId: 11,
      },
      {
        appointmentId: 12,
        purpose: "Follow Up",
        dateTime: "2026-01-06 15:17:04",
        status: "Cancelled",
        doctorId: 3,
        patientId: 12,
      },
      {
        appointmentId: 13,
        purpose: "Follow Up",
        dateTime: "2024-08-29 03:46:18",
        status: "Scheduled",
        doctorId: 3,
        patientId: 13,
      },
      {
        appointmentId: 14,
        purpose: "General Care",
        dateTime: "2025-05-25 07:38:11",
        status: "Scheduled",
        doctorId: 5,
        patientId: 14,
      },
      {
        appointmentId: 15,
        purpose: "Consultation",
        dateTime: "2025-07-06 20:02:40",
        status: "Cancelled",
        doctorId: 3,
        patientId: 15,
      },
      {
        appointmentId: 16,
        purpose: "Diagnostic & Testing",
        dateTime: "2024-11-20 17:47:05",
        status: "Completed",
        doctorId: 1,
        patientId: 16,
      },
      {
        appointmentId: 17,
        purpose: "General Care",
        dateTime: "2025-03-08 17:22:16",
        status: "Cancelled",
        doctorId: 2,
        patientId: 17,
      },
      {
        appointmentId: 18,
        purpose: "General Care",
        dateTime: "2024-12-18 00:54:10",
        status: "Cancelled",
        doctorId: 5,
        patientId: 18,
      },
      {
        appointmentId: 19,
        purpose: "General Care",
        dateTime: "2025-08-26 18:08:50",
        status: "Scheduled",
        doctorId: 4,
        patientId: 19,
      },
      {
        appointmentId: 20,
        purpose: "Follow Up",
        dateTime: "2026-05-03 04:31:32",
        status: "Scheduled",
        doctorId: 2,
        patientId: 20,
      },
    ],
    { ignoreDuplicates: true }
  );

  // Seed billing
  await db.Billing.bulkCreate(
    [
      {
        billId: 1,
        treatmentFee: 506.34,
        medicationFee: 138.99,
        labTestFee: 28.57,
        consultationFee: 61.57,
        totalAmount: 735.47,
        paymentStatus: "Paid",
        receptionistId: 20,
        patientId: 1,
      },
      {
        billId: 2,
        treatmentFee: 629.6,
        medicationFee: 23.45,
        labTestFee: 215.27,
        consultationFee: 82.38,
        totalAmount: 950.7,
        paymentStatus: "Paid",
        receptionistId: 16,
        patientId: 2,
      },
      {
        billId: 3,
        treatmentFee: 873.67,
        medicationFee: 54.01,
        labTestFee: 79.02,
        consultationFee: 417.94,
        totalAmount: 1424.64,
        paymentStatus: "Paid",
        receptionistId: 17,
        patientId: 3,
      },
      {
        billId: 4,
        treatmentFee: 751.02,
        medicationFee: 443.54,
        labTestFee: 177.1,
        consultationFee: 183.65,
        totalAmount: 1555.31,
        paymentStatus: "Unpaid",
        receptionistId: 19,
        patientId: 4,
      },
      {
        billId: 5,
        treatmentFee: 271.37,
        medicationFee: 66.53,
        labTestFee: 135.0,
        consultationFee: 282.97,
        totalAmount: 755.87,
        paymentStatus: "Paid",
        receptionistId: 19,
        patientId: 5,
      },
      {
        billId: 6,
        treatmentFee: 706.03,
        medicationFee: 492.4,
        labTestFee: 38.54,
        consultationFee: 271.44,
        totalAmount: 1508.41,
        paymentStatus: "Paid",
        receptionistId: 18,
        patientId: 6,
      },
      {
        billId: 7,
        treatmentFee: 323.79,
        medicationFee: 111.3,
        labTestFee: 140.1,
        consultationFee: 282.03,
        totalAmount: 857.22,
        paymentStatus: "Unpaid",
        receptionistId: 18,
        patientId: 7,
      },
      {
        billId: 8,
        treatmentFee: 324.83,
        medicationFee: 463.17,
        labTestFee: 138.51,
        consultationFee: 523.74,
        totalAmount: 1450.25,
        paymentStatus: "Paid",
        receptionistId: 20,
        patientId: 8,
      },
      {
        billId: 9,
        treatmentFee: 145.53,
        medicationFee: 499.66,
        labTestFee: 252.45,
        consultationFee: 582.95,
        totalAmount: 1480.59,
        paymentStatus: "Paid",
        receptionistId: 17,
        patientId: 9,
      },
      {
        billId: 10,
        treatmentFee: 465.77,
        medicationFee: 251.05,
        labTestFee: 260.75,
        consultationFee: 546.34,
        totalAmount: 1523.91,
        paymentStatus: "Unpaid",
        receptionistId: 17,
        patientId: 10,
      },
      {
        billId: 11,
        treatmentFee: 101.94,
        medicationFee: 207.4,
        labTestFee: 278.69,
        consultationFee: 481.82,
        totalAmount: 1069.85,
        paymentStatus: "Unpaid",
        receptionistId: 18,
        patientId: 11,
      },
      {
        billId: 12,
        treatmentFee: 726.93,
        medicationFee: 370.64,
        labTestFee: 237.17,
        consultationFee: 414.03,
        totalAmount: 1748.77,
        paymentStatus: "Paid",
        receptionistId: 19,
        patientId: 12,
      },
      {
        billId: 13,
        treatmentFee: 270.91,
        medicationFee: 124.5,
        labTestFee: 26.96,
        consultationFee: 454.66,
        totalAmount: 877.03,
        paymentStatus: "Unpaid",
        receptionistId: 16,
        patientId: 13,
      },
      {
        billId: 14,
        treatmentFee: 151.45,
        medicationFee: 300.41,
        labTestFee: 155.83,
        consultationFee: 519.0,
        totalAmount: 1126.69,
        paymentStatus: "Paid",
        receptionistId: 17,
        patientId: 14,
      },
      {
        billId: 15,
        treatmentFee: 964.7,
        medicationFee: 58.45,
        labTestFee: 63.89,
        consultationFee: 377.27,
        totalAmount: 1464.31,
        paymentStatus: "Unpaid",
        receptionistId: 17,
        patientId: 15,
      },
      {
        billId: 16,
        treatmentFee: 207.9,
        medicationFee: 447.34,
        labTestFee: 81.4,
        consultationFee: 376.99,
        totalAmount: 1113.63,
        paymentStatus: "Paid",
        receptionistId: 20,
        patientId: 16,
      },
      {
        billId: 17,
        treatmentFee: 477.3,
        medicationFee: 300.16,
        labTestFee: 161.61,
        consultationFee: 564.09,
        totalAmount: 1503.16,
        paymentStatus: "Unpaid",
        receptionistId: 17,
        patientId: 17,
      },
      {
        billId: 18,
        treatmentFee: 314.82,
        medicationFee: 209.98,
        labTestFee: 204.79,
        consultationFee: 215.0,
        totalAmount: 944.59,
        paymentStatus: "Paid",
        receptionistId: 18,
        patientId: 18,
      },
      {
        billId: 19,
        treatmentFee: 108.38,
        medicationFee: 318.16,
        labTestFee: 173.27,
        consultationFee: 104.99,
        totalAmount: 704.8,
        paymentStatus: "Paid",
        receptionistId: 20,
        patientId: 19,
      },
      {
        billId: 20,
        treatmentFee: 555.3,
        medicationFee: 83.58,
        labTestFee: 111.21,
        consultationFee: 87.84,
        totalAmount: 837.93,
        paymentStatus: "Unpaid",
        receptionistId: 17,
        patientId: 20,
      },
    ],
    { ignoreDuplicates: true }
  );

  // Seed medical_records
  await db.Medical_record.bulkCreate(
    [
      {
        record_id: 1,
        prescription: "Four part by son easy south.",
        diagnosis: "Or idea impact green same.",
        lab_result: "Abnormal",
        treatment: "Oil never instead military per quickly.",
        patientId: 1,
        appointmentId: 1,
      },
      {
        record_id: 2,
        prescription: "Country she to true start.",
        diagnosis: "Property agreement minute.",
        lab_result: "Pending",
        treatment: "Difficult new line.",
        patientId: 2,
        appointmentId: 2,
      },
      {
        record_id: 3,
        prescription: "Article analysis western lot.",
        diagnosis: "Successful act anyone hand success.",
        lab_result: "Normal",
        treatment: "Fact ready force national.",
        patientId: 3,
        appointmentId: 3,
      },
      {
        record_id: 4,
        prescription: "Laugh just begin especially her north.",
        diagnosis: "Citizen no series civil.",
        lab_result: "Abnormal",
        treatment: "Past position buy me remember.",
        patientId: 4,
        appointmentId: 4,
      },
      {
        record_id: 5,
        prescription: "Enjoy develop defense bank majority bill.",
        diagnosis: "Reality thus billion condition.",
        lab_result: "Pending",
        treatment: "Style possible national blood exactly rich.",
        patientId: 5,
        appointmentId: 5,
      },
      {
        record_id: 6,
        prescription: "Remember feel increase.",
        diagnosis: "Adult support name paper.",
        lab_result: "Pending",
        treatment: "We wish third head according.",
        patientId: 6,
        appointmentId: 6,
      },
      {
        record_id: 7,
        prescription: "Government truth base value need.",
        diagnosis: "Movement under building.",
        lab_result: "Abnormal",
        treatment: "Always simple individual deal store although.",
        patientId: 7,
        appointmentId: 7,
      },
      {
        record_id: 8,
        prescription: "Do property change.",
        diagnosis: "Line significant.",
        lab_result: "Normal",
        treatment: "Avoid run along develop also measure.",
        patientId: 8,
        appointmentId: 8,
      },
      {
        record_id: 9,
        prescription: "Cost point service beyond.",
        diagnosis: "Why bank.",
        lab_result: "Pending",
        treatment: "Skill still interview brother.",
        patientId: 9,
        appointmentId: 9,
      },
      {
        record_id: 10,
        prescription: "Newspaper smile six.",
        diagnosis: "Night deep garden.",
        lab_result: "Pending",
        treatment: "Over consumer police capital those occur.",
        patientId: 10,
        appointmentId: 10,
      },
      {
        record_id: 11,
        prescription: "Per often risk generation seven.",
        diagnosis: "Lead recently happy yard.",
        lab_result: "Pending",
        treatment: "Population one argue against time happen.",
        patientId: 11,
        appointmentId: 11,
      },
      {
        record_id: 12,
        prescription: "Stop media series amount.",
        diagnosis: "Make turn yourself service.",
        lab_result: "Normal",
        treatment: "Table career such move.",
        patientId: 12,
        appointmentId: 12,
      },
      {
        record_id: 13,
        prescription: "Behavior quickly machine imagine one.",
        diagnosis: "Heavy there home nearly option.",
        lab_result: "Pending",
        treatment: "Benefit model season sit class race few.",
        patientId: 13,
        appointmentId: 13,
      },
      {
        record_id: 14,
        prescription: "Gun account result.",
        diagnosis: "Key low guy development well.",
        lab_result: "Abnormal",
        treatment: "Control material whatever he suddenly far could.",
        patientId: 14,
        appointmentId: 14,
      },
      {
        record_id: 15,
        prescription: "Spend behavior face between.",
        diagnosis: "Cell election way drive.",
        lab_result: "Abnormal",
        treatment: "Keep shoulder speak meet science.",
        patientId: 15,
        appointmentId: 15,
      },
      {
        record_id: 16,
        prescription: "Town together voice forget cell price.",
        diagnosis: "Travel professional into memory receive.",
        lab_result: "Pending",
        treatment: "Area sign discover thing sing.",
        patientId: 16,
        appointmentId: 16,
      },
      {
        record_id: 17,
        prescription: "Education ago western thought.",
        diagnosis: "Every seek very three factor.",
        lab_result: "Pending",
        treatment: "Travel computer although former hotel.",
        patientId: 17,
        appointmentId: 17,
      },
      {
        record_id: 18,
        prescription: "Only I million per detail.",
        diagnosis: "Face run.",
        lab_result: "Abnormal",
        treatment: "Quality political imagine tell.",
        patientId: 18,
        appointmentId: 18,
      },
      {
        record_id: 19,
        prescription: "Company while shoulder weight.",
        diagnosis: "Scene difficult now recognize.",
        lab_result: "Abnormal",
        treatment: "Most time hand officer.",
        patientId: 19,
        appointmentId: 19,
      },
      {
        record_id: 20,
        prescription: "Hotel security result resource.",
        diagnosis: "Skill yes difficult rise according.",
        lab_result: "Pending",
        treatment: "Great claim leave stand whatever though water.",
        patientId: 20,
        appointmentId: 20,
      },
    ],
    { ignoreDuplicates: true }
  );
}
